### ISSUE TITLE
sVB IDE with double lettering ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#16]
Hi Mohammad,

is it correct that there is a double lettering at the top left ->"FiveStar_With_Color1.sb"? Please, have a look at it!

Regards ... Gregor

![Screenshot IDE sVB](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/b4341c78-0bb3-42ba-abf7-9c45bd643a6b)

**Comment by VBAndCs** [comment]
Yes, it is the text shadow. Actually, this is the original design from Small Basic, but it caused me many troubles when I made some modifications, so, I kept it this way. I may look into it again.
By the way, try this:
```
GraphicsWindow.Width = 700
GraphicsWindow.BackgroundColor = Colors.Green
GraphicsWindow.FontBold = True
GraphicsWindow.FontSize = 60
'draw a black shadow texts
GraphicsWindow.PenColor = Colors.Black
GraphicsWindow.BrushColor = Colors.Black
For I = 1 To 25
   Txt = Shapes.AddText("Small Visual Basic")
   Shapes.Animate(Txt, 92, 142, 2000 + I * 50)
Next
' draw white text shifted by (8,8)
GraphicsWindow.PenColor = Colors.White
GraphicsWindow.BrushColor = Colors.White
Txt = Shapes.AddText("Small Visual Basic")
Shapes.Animate(Txt, 100, 150, 2000)
```

![image](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/48354902/0df0b968-855d-4991-8314-c578bae66812)

**Comment by boa2145** [comment]
Hi Mohammad, this text effect is great. I tried it out and I will modify some elements. Regards ... Gregor

**Comment by VBAndCs** [comment]
Done in[sVB 2.8.4.4](https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller)
Thanks.
