### ISSUE TITLE
Small Visual Basic has arrived on Tumblr ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#19]
Hello, My last post #139 that I published on my channel "Small-Basic-Programming" on Tumblr. Next time I will often use the sVB IDE to program and to show my code snippets  on this social media platform. So it's also possible to advertise sVB there. Hopefully I'll be able to learn the visual part of the programming language sVB, too. Regards ... Gregor

[Small-Basic-Programming on Tumblr (website view)](https://small-basic-programming.tumblr.com)

[Small-Basic-Programming on Tumblr (community view)](https://www.tumblr.com/blog/small-basic-programming)

![Tumblr Small Basic Post 139 1](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/32256211-ce6f-4e2c-8a24-53fa44455f04)
![Tumblr Small Basic Post 139 2](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/66ed5242-e8d0-4737-bebd-62c14680ba0c)

**Comment by VBAndCs** [comment]
@boa2145 
Thanks for your efforts. Could you please provide a link?
