### ISSUE TITLE
Where's the original editor code?

### ISSUE THREAD

**Issue by Caseysch** [VBAndCs/sVB-Small-Visual-Basic#20]
Hey @VBAndCs , where did you get the original Small Basic editor code? I didn't realize that was open source and I'm trying to find the repo.

**Comment by VBAndCs** [comment]
@Caseysch 
As I mentioned, I had to prove the concept myself, after I asked for this in the SB repo since Dec 25, 2020:
https://github.com/sb/smallbasic-editor/issues/172
Unfortunately, no one cared!
I hope MS take SB to the next level. I've just proved it is easy.
Thanks.
