### ISSUE TITLE
History of issues ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#22]
Hello Mohammad, is it possible to see a history of all issues? Regards ... Gregor

**Comment by VBAndCs** [comment]
@boa2145 
If I got this right, I think you can look at the [closed issues page](https://github.com/VBAndCs/sVB-Small-Visual-Basic/issues?q=is%3Aissue+is%3Aclosed).
Thanks

**Comment by boa2145** [comment]
@VBAndCs Okay, I see that "closed issues page". Thx.
