### ISSUE TITLE
The length and height of a text in graphics mode ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#25]
Hi Mohammad,

I sometimes need the length and height of a text in "Graphics mode" when using "GraphicsWindow" with "DrawText()" or "DrawBoundText()". How can I calculate the length and height of a text depending on the font name and font size?

Regards ... Gregor

**Comment by VBAndCs** [comment]
@boa2145 
You can't. But you can quite the DrawText method, and start using the `Controls.AddLabel` method to draw the text in a lable and have full control of it. You can change the font properties of the label, then call the `FitContentSize` to force the label to resize its width and height to fit its text, so you can use its Width and Height properties to get the text size.
Note that sVB allow you to draw all controls (except menus) on the Graphics Window.
Try this:
```vb
Lbl = Controls.AddLabel("Hello sVB", 100, 100)
Lbl.FontSize = 20
Lbl.FitContentSize()
GraphicsWindow.ShowMessage(
   Text.Format(
      "Width = [1], Height = [2]",
      {Lbl.Width, Lbl.Height}
   ),
   "Text size"
)
```

![image](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/48354902/27a653f2-1793-4311-a898-e566aa66f9b3)

**Comment by VBAndCs** [comment]
Note also that sVB controls has more animation methods than the SB shapes, so, you can do a lot of amazing things with the text, like:
```vb
Lbl.AnimateAngle(50, 1000)
```
