### ISSUE TITLE
DrawText() and DrawBoundText() for forms ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#30]
Good morning Mohammand,

could you, please, explain why you did not implement the methods DrawText() and DrawBoundText() for forms? I'd like to use theses both methods for forms , too. 

In Small Basic there are not labels, but I can use these two methods to output text on GraphicsWindow. So, I appreciate these methods DrawText() and DrawBoundText() on GraphicsWindow, but I miss labels there. When I use a form with sVB, I appreciate labels, but I miss DrawText() and DrawBoundText(). The advantage of DrawText() and DrawBoundText() for forms could be that I don't have to handle with labels before to put out text on forms. For me it would be better to use both on forms: labels and DrawBoundText() resp. DrawText().

Have a nice day ... Gregor

**Comment by VBAndCs** [comment]
@boa2145 
I see no use of these tow functions on the form. Labels are perfect in displaying text, and you can add them on the form in runtime if you want by calling:
```
n=n+1
newLabel = Me.AddLabel("newlabel" + n,  left, top, width, height)
newLabel.FontSize= 16
newLabel.Text = "Hello"
```

**Comment by boa2145** [comment]
Hello Mohammad,

In the meantime I've tried different ways to output text in a form. I also think, that a label is the best way for displaying text in a form. 

However, I still have problems with displaying text by using a label, waiting a bit and then letting it disappear again. This did not work correctly with "LabelName.Visible = True/False" and "Delay()" or "WinDelay()". I think it's better to avoid Delay() and WinDelay() in event-driven programs. What do you think about it?

Regards ... Gregor

**Comment by VBAndCs** [comment]
@boa2145 
Please show me a sample to get what you mean.

**Comment by boa2145** [comment]
See above, please. Everything is fine, Mohammad.
