### ISSUE TITLE
Drawing a x-pointed star with thick lines and correct points ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#31]
Hello Mohammad,

I want to draw a five-pointed star with thick lines and I have the problem, that I cannot draw such a star with correct points at the ends. So I enclose two screenshots with turtle programming via sVB and via Python. You see the different ends of the lines. Is it possible to draw a five-pointed star with correct points?

Regards ... Gregor

sVB:
![FiveStar_sVB](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/e7919eec-8c83-41a8-bddb-ce80ddc19665)

Python:
![FiveStar_Python](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/3cc84b54-2193-433c-b1ea-0e27186ef027)

**Comment by VBAndCs** [comment]
@boa2145 
Yes. Fill the figure, and it will be fixed! And don't ask me Why! You can fill the figure with a transparent color if you want:
```vb
Jags = 5
Turtle.X = 300
Turtle.Y = 300
Turtle.Speed = 30
GW.PenWidth = 20
Turtle.CreateFigure()
For I = 1 To Jags
   Turtle.Move(100)
   Turtle.Turn(2 * 360 / Jags)
   Turtle.Move(100)
   Turtle.Turn(-360 / Jags)
Next
GraphicsWindow.BrushColor = Colors.Transparent
Turtle.FillFigure()
```

![image](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/48354902/ae9a320a-ec1b-41d4-8eb2-65c3419eb36f)

**Comment by boa2145** [comment]
Good morning Mohammad,

Thanks for your reply with the source code and its output. I didn't know that I can fill a form with a transparent color. That's great, but there was still a tiny mistake. I enclose two pics to demonstrate it. If you hide the turtle at the end of the source code, you'll see it. I found a solution. You have to add a last move by the turtle outside the loop with the same length and it was fixed.

Regards ... Gregor

Your source code:
![Your Source Code](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/878be4d1-99b2-49cd-8abf-07a1a9f18a2b)

The output of your source code:
![Your FiveStar](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/e8d99fd2-431d-4581-8884-c26e747d9c5d)

My added source code:
![Added Source Code](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/ef992857-a0bd-4df0-8606-3eb74778ea48)

The output of my added source code:
![Corrected FiveStar](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/8163e033-9a3f-454c-aaee-1609600b3fa9)
