### ISSUE TITLE
Is there any way to remove image of label?

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#46]
Version: 2.8.8.1
Details:
Couldn't find a way to remove image of label.
Step1: Drag one label, two buttons onto the form.
Step2: Input code as below:
```Small Visual Basic
'------------------------------------------------
Sub Button1_OnClick()
   Label1.Image = "D:\1.jpg"
EndSub

'------------------------------------------------
Sub Button2_OnClick()
   Label1.Image = ""
   
EndSub
```

Step3: Run the form
Result：Button2 cann't remove image of the label. The empty string should cancel the image.

Screenshot:
![2024-01-08_195425](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/120c20ed-17a4-49e8-a6b4-f4a743d48b2e)

**Comment by VBAndCs** [comment]
Yes. Set its text.
Label1.Text=""

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: dynamicboy ***@***.***>
Sent: Monday, January 8, 2024 1:56:53 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Is there any way to remove image of label? (Issue #46)


Version: 2.8.8.1
Details:
Couldn't find a way to remove image of label.
Step1: Drag one label, two buttons onto the form.
Step2: Input code as below:

'------------------------------------------------
Sub Button1_OnClick()
   Label1.Image = "D:\1.jpg"
EndSub

'------------------------------------------------
Sub Button2_OnClick()
   Label1.Image = ""

EndSub


Step3: Run the form
Result：Button2 cann't remove image of the label. The empty string should cancel the image.

Screenshot:
2024-01-08_195425.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/120c20ed-17a4-49e8-a6b4-f4a743d48b2e>
