### ISSUE TITLE
Turtle stamp function for sVB ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#55]
Hello Mohammad,

I would like to suggest to implement the turtle stamp function for sVB. This function is sometimes useful if you want to set a mark with the turtle, like a finger print. The Turtle library for Python already has this stamp function that you can set depending on the shape of the turtle.

"This method is used to stamp a copy of the turtleshape onto the canvas and return its id. It doesn’t require any argument. Whatever the shape of the turtle is, it is printed at that point and continues with the next instructions." (GeeksForGeeks)

Regards ... Gregor

**Comment by VBAndCs** [comment]
Hi Gregor,
I am not sure what you are asking or what it can be used for, but I am sure that I can't do anything more about turtles at the moment.
The BASIC's 60th anniversary is after 2.5 months, and I wish I can release sVB 3.0 by that time with the debugger featured added.
Thanks.
________________________________
From: Gregor ***@***.***>
Sent: Tuesday, February 13, 2024 8:25 PM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Turtle stamp function for sVB ... (Issue #55)


Hello Mohammad,

I would like to suggest to implement the turtle stamp function for sVB. This function is sometimes useful if you want to set a mark with the turtle, like a finger print. The Turtle library for Python already has this stamp function that you can set depending on the shape of the turtle.

"This method is used to stamp a copy of the turtleshape onto the canvas and return its id. It doesn’t require any argument. Whatever the shape of the turtle is, it is printed at that point and continues with the next instructions." (GeeksForGeeks)

Regards ... Gregor

**Comment by boa2145** [comment]
Hi Mohammad, I understand that you have to focus on your current debugger project for sVB around the BASIC's 60th anniversary. It is an important date for BASIC enthusiasts and I am looking foward to find some interesting interviews, articles or blogs on the internet. I have a lot of old and valuable BASIC books and floppy discs 
since the early 1970s. I want to present them to the computer museum in Kiel or Oldenburg in Germany as my estate one day. Good luck for you debugging project ... Gregor 

![Kurtz Kemeny Back To Basic 1](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/cd1bdb82-370d-4185-b3b9-9299af928679)
![Kurtz Kemeny Back To Basic 2](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/113761330/6e200d63-8d3c-41c3-94e6-c44c8c421f83)
