### ISSUE TITLE
The method "Pause()" doesn't work with sVB ...

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#57]
Hello Mohammad,

I noticed that the method "Pause()" of the object "TextWindow()" doesn't work with Small Visual Basic 2.8.9.3. I also tested it with Small Basic and the "Pause()" method works there. Do you have an explanation for this?

Regards ... Gregor

**Comment by VBAndCs** [comment]
Pause is called by the PauseIfVisible, and this method is added to the exe to keep it running and I wanted to force the program to close after closing the form.
I can fix the Pause but I will make PauseIfVisible close the window. Can you tell me some important usage of pause?
Have you ever used PauseIfVisible?
________________________________
From: Gregor ***@***.***>
Sent: Saturday, February 24, 2024 9:57 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] The method "Pause()" doesn't work with sVB ... (Issue #57)


Hello Mohammad,

I noticed that the method "Pause()" of the object "TextWindow()" doesn't work with Small Visual Basic 2.8.9.3. I also tested it with Small Basic and the "Pause()" method works there. Do you have an explanation for this?

Regards ... Gregor

**Comment by boa2145** [comment]
Good evening Mohammad, I tried the Pause() and PausIfVisible() methods on SB and sVB. For SB, both methods work for the current text window. I press a key and the source code continues and the text window stays open. However, when I try out the two functions in sVB, "Press any key to continue" also appears, but I can make visible keyboard inputs and after using <Enter> the text window is closed immediately, even if the source text continues.

I only need these two methods as part of a Small Basic tutorial I'm currently working through. These two methods are explained and used there. If you ask me, I would also offer both methods in sVB since your program was set on SB. Both methods belong to SB, I would also offer them in sVB. It may lead to uncertainty among users if they try to use methods that do not work properly. And empty methods don't make sense to me. This is my opinion on this topic.

**Comment by VBAndCs** [comment]
Hi Gregor ,
I never needed these two methods, but I've fixed the pause method, bit will hide the PuaseIfVisible one, as I don't see why it is important to users. This change will be available in the next version.
Thanks.


________________________________

**Comment by boa2145** [comment]
Yes, I understand, Mohammad. Thanks for the hint to use the method "PauseWithoutMessage" and to create my own message by using the method TW.Write(). Good night!

**Comment by boa2145** [comment]
Good morning Mohammad, Thanks for fixing the "WriteLine.Pause()" method. Have a nice week ... Gregor

**Comment by VBAndCs** [comment]
Hi Gregor,

Yor're welcome.

In the next version, I will also bring back the PauseIfVisible, with a new PauseThenClose method, because I had disable the console window close button to prevent it from closing the sVB IDE in the debugging mode!

PauseThenClose (it rhymes :D) shows a slightly deferent message (Press any key to close) so it is also the perfect method to use in the exe startup instead of PauseIfVisible, so I can keep the original methods functionality as was SB.

regards.

________________________________
