### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by ga6939russell** [VBAndCs/sVB-Small-Visual-Basic#7]
I have tried to download to Windows 10 Home. Security will not let me download and I can't seem to find any overrides to the blockage.

**Comment by VBAndCs** [comment]
@ga6939russell 
If the file is already downloaded (and I think it must, otherwise windows will have no idea what it is), right-click on the downloaded file and then select Properties. In the General tab, click Unblock, click Apply and then click OK..

**Comment by ga6939russell** [comment]
It's not downloaded. I checked!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VBAndCs** [comment]
You may have a more restricted fire wall or antivirus. 
Anyway, I will publish the sVB installer on VB marketplace in a few hours, so you can try with it. I will notify you then.

**Comment by VBAndCs** [comment]
@ga6939russell 
Try to get the installer from:
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller
