### ISSUE TITLE
Dialogs.InputBox causes a runtime error in debug mode

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#72]
![2024-07-09_173438](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/e2bdad21-31a5-47ef-9ef2-b1c62a7d035e)

**Comment by VBAndCs** [comment]
I fixed it, and the fix will be available in the next release.
Don't forget to close this issue.
Thanks.

________________________________
From: dynamicboy ***@***.***>
Sent: Tuesday, July 9, 2024 9:49 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Dialogs.InputBox causes a runtime error in debug mode (Issue #72)


2024-07-09_173438.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/e2bdad21-31a5-47ef-9ef2-b1c62a7d035e>
