### ISSUE TITLE
Sometimes Can't set GraphicsWindow.BrushColor

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#73]
version: sVB 3.0.7.6
details: Sometimes Can't set GraphicsWindow.BrushColor

![2024-07-09_180230](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/50e3b945-26c1-45de-b9c6-890be0388eb9)

I use a label , it's background color to represent user's color choice, but sometimes i can't set it's backcolor to graphicswindow.brushcolor.

**Comment by VBAndCs** [comment]
You code works fine on my PC. Please provide detailed steps to produce this error. You may also attach the whole project as a zip file by dropping it on the replay box here.

________________________________
From: dynamicboy ***@***.***>
Sent: Tuesday, July 9, 2024 10:07 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Sometimes Can't set GraphicsWindow.BrushColor (Issue #73)


version: sVB 3.0.7.6
details: Sometimes Can't set GraphicsWindow.BrushColor

2024-07-09_180230.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/50e3b945-26c1-45de-b9c6-890be0388eb9>

I use a label , it's background color to represent user's color choice, but sometimes i can't set it's backcolor to graphicswindow.brushcolor.

**Comment by VBAndCs** [comment]
I am waiting for more details so I can fix this issue before publishing a new update.
________________________________
From: dynamicboy ***@***.***>
Sent: Tuesday, July 9, 2024 10:07 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Sometimes Can't set GraphicsWindow.BrushColor (Issue #73)


version: sVB 3.0.7.6
details: Sometimes Can't set GraphicsWindow.BrushColor

2024-07-09_180230.png (view on web)<https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/50e3b945-26c1-45de-b9c6-890be0388eb9>

I use a label , it's background color to represent user's color choice, but sometimes i can't set it's backcolor to graphicswindow.brushcolor.

**Comment by dynamicboy** [comment]
[字幕截图生成器.zip](https://github.com/user-attachments/files/16216142/default.zip)

I apologize for the delay. My GitHub connection is unstable, and other work tasks have been occupying my time.
This is a fake movie screenshot created with a customizable subtitle generator application for entertainment purposes.
In debug mode, the error I mentioned earlier may occur after selecting a color.

**Comment by dynamicboy** [comment]
![2024-07-14_165120](https://github.com/user-attachments/assets/5253b67b-6cc0-4271-85f1-b46ee9fcc535)
screenshot with English explanation.

**Comment by dynamicboy** [comment]
[GBLib.zip](https://github.com/user-attachments/files/16216261/GBLib.zip)
My small library for the project.

**Comment by VBAndCs** [comment]
This lib can't help me. I want the sample code that caused the error so I can know what is happening.
________________________________

**Comment by dynamicboy** [comment]
The whole project is in "[字幕截图生成器.zip](https://github.com/user-attachments/files/16216142/default.zip)" file.
The sample code that throw error is in file Form1.sb, line number is 119.

**Comment by VBAndCs** [comment]
There is no Form1.sb in the zip file. You sent only the bin folder that contains an exe file and some dlls
________________________________

**Comment by dynamicboy** [comment]
The whole project is indeed in "[字幕截图生成器.zip](https://github.com/user-attachments/files/16216142/default.zip)" file.
The sample code that throw error is in file Form1.sb, line number is 119.

To run this project, you may need add my little libraries for sVB.
They are GBImage.dll, GBLibrary.dll and sVB project GBLib which is in [GBLib.zip](https://github.com/user-attachments/files/16216261/GBLib.zip) file.

**Comment by VBAndCs** [comment]
Sorry! I didn't pay attention to the Chinese file.
I've fixed the bug. You can try the fix in the sVB 3.0.7.8:
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller
If everything is OK, then [lease close this issue.
Thanks
________________________________
