### ISSUE TITLE
Using trigonometric functions with sVB ?

### ISSUE THREAD

**Issue by boa2145** [VBAndCs/sVB-Small-Visual-Basic#80]
Hello Mohammad,

Is it possible to calculate trigonometric functions with sVB, i.e. adjacent side, opposite side, hypotenus and the angles alpha and beta? I can calculate trigonometric functions (sine, cosine, tangent) with my calculator, but I don't know how this could work with sVB, e.g. how can I calculate the angle alpha with tangent alpha = 1.488 => alpha = 56.0996 degrees?

Regards ... Gregor

**Comment by VBAndCs** [comment]
All math function belong to the Math classs, which contains Sin, Cos, Tan, and their reverse fubctions: ArcSin, ArcCos and ArcTan.
By default all these functions use radian angles (as inherited from SB) and you should convert from and to degrees using calculations or the given math methods. But I made this easy in sVB by propviding the option:
Math.UseRadianAngles = False
to make all subsequent calls to those functions use degrees.
Thanks.
________________________________
From: Gregor ***@***.***>
Sent: Sunday, August 25, 2024 7:05 AM
To: VBAndCs/sVB-Small-Visual-Basic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VBAndCs/sVB-Small-Visual-Basic] Using trigonometric functions with sVB ? (Issue #80)


Hello Mohammad,

is it possible to calculate trigonometric functions with sVB, i.e. adjacent side, opposite side, hypotenus and the angles alpha and beta? I can calculate trigonometric functions (sine, cosine, tangent) with my calculator, but I don't know how this could work with sVB, e.g. how can I calculate, for example, the angle alpha with tangent alpha = 1.488 => alpha = 56.0996 degrees?

Regards ... Gregor

**Comment by boa2145** [comment]
Hello Mohammad, Thx for your hints. I now have to compare how it works with the calculator and with the mathematical functions of Small Visual Basic. I haven't dealt with angular functions that often in the various programming languages ​​(Python, Scratch, Small Basic). I usually calculate with degrees, less with radians. Then I will use the "Math.UseRadianAngles" to set this option to false. Have a nice day ... Gregor :)

**Comment by boa2145** [comment]
Now I was able to use the radians and dregrees for calculating sin, cos, tan and their reverse functions. But - what shall I do with the property "Math.UseRadianAngles = False"? Small Visual Basic doesn't know this property.

**Comment by VBAndCs** [comment]
This property is added in recent versions, so make sure you have the latest sVB version.
I just published sVB 3.0.8.5 to add mores samples. You will find new interesting samples in the "Tertile samples" folder. In most of these samples I use the statement:
Math.UseRadianAngles = False
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller

________________________________
