### ISSUE TITLE
Weird Sting!

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#82]
version: sVB 3.0.8.4
code:

```Small Visual Basic
TeamName = "山东高速"
InputFullName = "高诗岩"

Query = Text.Format("SELECT FullName FROM Players WHERE Team='[1]' And FullName='[2]';", {TeamName, InputFullName})
TW.WriteLine("query = " + Query)


Query = "SELECT FullName FROM players WHERE Team='" + TeamName + "' AND FullName='" + InputFullName + "';"
TW.WriteLine("query = " + Query)


Query = "SELECT FullName FROM players WHERE Team '" + TeamName + "' AND FullName '" + InputFullName + "';"
TW.WriteLine("query = " + Query)
```

output:
query = SELECT FullName FROM Players WHERE Team=e\='高诗岩'\;;
query = SELECT FullName FROM players WHERE Team=e\='高诗岩'\;;
query = SELECT FullName FROM players WHERE Team '山东高速' AND FullName '高诗岩';

it should be:
query = SELECT FullName FROM Players WHERE Team='山东高速' And FullName='高诗岩';

**Comment by dynamicboy** [comment]
output screenshot:
![2024-09-10_032528](https://github.com/user-attachments/assets/c81c49c3-b602-4781-88c1-bf024fbee062)

**Comment by dynamicboy** [comment]
I found string concatenation is correct in TW.WriteLine

**Comment by dynamicboy** [comment]
version 3.0.9.3 remains the same

**Comment by VBAndCs** [comment]
No, it is not. You just didn't add the = before the '
Try this and you will get the same reesult:
Query = "SELECT FullName FROM players WHERE Team='" + TeamName + "' AND FullName='" + InputFullName + "';"


________________________________

**Comment by dynamicboy** [comment]
' OK
Query = "SELECT FullName FROM players WHERE Team='" + TeamName + "' AND FullName='" + InputFullName + "';"
TW.WriteLine(Query)


' Not OK
Query = "SELECT FullName FROM players WHERE Team='" + TeamName + "' AND FullName='" + InputFullName + "';"
TW.WriteLine("anyString:" + Query)

' Not OK
Query = Text.Format("SELECT FullName FROM Players WHERE Team='[1]' And FullName='[2]';", {TeamName, InputFullName})
TW.WriteLine(Query)

outputs:
SELECT FullName FROM players WHERE Team='山东高速' AND FullName='高诗岩';
anyString:SELECT FullName FROM players WHERE Team=e\='高诗岩'\;;
SELECT FullName FROM Players WHERE Team=e\='高诗岩'\;;

I prefer Text.Format to compose complex sql queries and commands. It doesn't work.

**Comment by VBAndCs** [comment]
This issue happens because the string contains = and ;, which are used in the array representation string in Small Basic, and I fixed the array parser to solve this problem.
________________________________
