### ISSUE TITLE
Could sVB update project bin folder with newer DLL and XAML files from lib folder based on file modification time?

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#86]
I encountered an issue while customizing the Dialog lib, where the updated DLL or XAML files in the lib folder were not reflected in the working project's bin folder, resulting in a 'control not found' error.

Could sVB be configured to update the project bin folder with newer DLL and XAML files from the lib folder based on file modification time?

**Comment by dynamicboy** [comment]
I currently delete the relevant files in the bin folder and rebuild the working project to get the updated library version.

**Comment by VBAndCs** [comment]
I think you can manage. Currently I have no plan to do this, but keep this one open for the future.
Thanks.
________________________________
