### ISSUE TITLE
Semicolon in either MsgBox text parameter causes both Title and Message to be blank

### ISSUE THREAD

**Issue by sjsepan3** [VBAndCs/sVB-Small-Visual-Basic#9]
OK:
      result = Dialogs.MsgBox(
         "Save Changes",
         "Do you want to save changes?"
      )

Not OK:
      result = Dialogs.MsgBox(
         "Save Changes; because",
         "Do you want to save changes?"
      )

Not OK:
      result = Dialogs.MsgBox(
         "Save Changes",
         "something changed; Do you want to save changes?"
      )

Also, when this happens, I sometimes spot the text "Label1" flash briefly in the message area.
I suppose a semicolon is being used in the parsing of the code, behind the scenes.

**Comment by VBAndCs** [comment]
@sjsepan3 
Thanks for reporting this.
SB, and also sVB, uses the  `;` in the string representation of the array, so I will review how this string is parsed to fix this issue in the next release.

**Comment by VBAndCs** [comment]
@sjsepan3 
I've fixed the bug, added a [test for it](https://github.com/VBAndCs/sVB-Small-Visual-Basic/blob/7f0a7f83ecf8bbfa6094cc05a821b8cec5f41986/sVB%20Tests/FrmArrayTests.sb#L451) ,and updated the [installer](https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller) to the sVB v2.8.3.
Thanks for helping improving sVB.

**Comment by sjsepan3** [comment]
> I've fixed the bug, added a [test for it](https://github.com/VBAndCs/sVB-Small-Visual-Basic/blob/7f0a7f83ecf8bbfa6094cc05a821b8cec5f41986/sVB%20Tests/FrmArrayTests.sb#L451) ,and updated the [installer](https://marketplace.visualstudio.com/items?itemName=ModernVBNET.sVBInstaller) to the sVB v2.8.3.
> Thanks for helping improving sVB.

Looks good; Thanks for all your work!
